# Generated by Django 5.2 on 2025-05-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "performance")},
        ),
    ]
