# Generated by Django 5.2 on 2025-05-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row",)},
        ),
    ]
